### ISSUE TITLE
Cannot find module '../dist/main'

### ISSUE THREAD

**Issue by nsaliu** [salsita/bunny-migrate#82]
Hi all,
and thank you for your work!

I've an issue trying to start the tool.

I do the current steps:

```
root@d8f88f78fced:/usr/src/app# npm i -g bunny-migrate
/usr/local/bin/bunny-migrate -> /usr/local/lib/node_modules/bunny-migrate/bin/bunny-migrate
+ bunny-migrate@1.3.1
added 50 packages from 40 contributors in 5.49s
```

but seems not work:
```
root@d8f88f78fced:/usr/src/app# bunny-migrate help
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '../dist/main'
Require stack:
- /usr/local/lib/node_modules/bunny-migrate/bin/bunny-migrate
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/bunny-migrate/bin/bunny-migrate:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/bunny-migrate/bin/bunny-migrate' ]
}
```

Info:
```
root@d8f88f78fced:/usr/src# npm -v
6.14.5
```

```
root@d8f88f78fced:/usr/src# node -v
v12.18.2
```

**Comment by dolezel** [comment]
Thanks for reporting!
Version `1.3.2` should fix this
